<?php

namespace KochTest\Config\Adapter;

use Koch\Config\Adapter\Native;
use org\bovigo\vfs\vfsStream;
use org\bovigo\vfs\vfsStreamDirectory;
use org\bovigo\vfs\vfsStreamWrapper;

class NativeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Native
     */
    protected $object;

    public function setUp()
    {
        $this->object = new Native;

        vfsStreamWrapper::register();
        $this->configFileURL = vfsStream::url('root/config.php');
        $this->file = vfsStream::newFile('config.php', 0777)->withContent($this->getConfigFileContent());
        $this->root = new vfsStreamDirectory('root');
        $this->root->addChild($this->file);
        vfsStreamWrapper::setRoot($this->root);
    }

    public function tearDown()
    {
        unset($this->object);
    }

    /**
     * @covers Koch\Config\Adapter\Native::readConfig
     */
    public function testReadConfig()
    {
        $array = $this->object->readConfig($this->configFileURL);
        $this->assertEquals($array, $this->getConfigArray());
    }

    /**
     * @covers Koch\Config\Adapter\Native::writeConfig
     */
    public function testWriteConfig()
    {
        $result = $this->object->writeConfig($this->configFileURL, $this->getConfigArray());
        $this->assertTrue($result);
    }

    public function getConfigFileContent()
    {
        return "<?php
        // Configuration File generated by Koch Framework.
        return array (
          'test' => 'value',
        );";
    }

    public function getConfigArray()
    {
        return array(
            'test' => 'value'
        );
    }
}
