before_commands:
    - composer self-update
    - composer install --dev

tools:
    php_cs_fixer: false
    php_code_sniffer:
        config:
            standard: PSR2
    php_mess_detector: false
    php_analyzer:
        filter:
            excluded_paths: ["*/tests/*", "*/vendor/*", , "*/bin/*"]
    sensiolabs_security_checker: false
