before_commands:
    - composer self-update
    - composer install --dev

tools:

    php_cs_fixer: false
        config:
            level: all
        filter:
            paths: [framework/*, tests/*]

    php_code_sniffer: false
        config:
            standard: PSR2
       filter:
            paths: [framework/*, tests/*]

    php_mess_detector: false

    php_analyzer: true
        filter:
            paths: [framework/*, tests/*]

    sensiolabs_security_checker: false
