#
# scrutinizer-ci.com Configuration File
#
# https://scrutinizer-ci.com/docs/
#
before_commands:
    - sudo composer self-update
    - composer install --dev --prefer-source

filter:
    excluded_paths:
        - 'vendor/*'

tools:

    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: [framework/*, tests/*]

    php_cpd:
        enabled: true
        #filter:
        #    paths: [framework/*, tests/*]

    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: [framework/*, tests/*]

    php_mess_detector:
        enabled: true
        #config:
        #    rulesets:
        #        - codesize
        #        - unusedcode
        #        - naming
        filter:
            paths: [framework/*, tests/*]

    php_analyzer:
        enabled: true
        filter:
            paths: [framework/*, tests/*]
        #config:
        #    checkstyle: ~
        #    verify_php_doc_comments: ~
        #    doc_comment_fixes: ~
#
        #path_configs:
        #    tests:
        #        paths: [tests/*]
        #        checkstyle: false
        #        verify_php_doc_comments: false
        #        doc_comment_fixes: false

    php_code_coverage:
        enabled: true
        test_command: phpunit -c tests/phpunit.xml.dist
        filter:
            paths: [framework/*, tests/*]

    sensiolabs_security_checker: false
