tools:
    php_cs_fixer: false
    php_code_sniffer:
        config:
            standard: PSR2
    php_mess_detector: false
    php_analyzer:
        filter:
            excluded_paths: ["*/Tests/*"]
    sensiolabs_security_checker: false
