before_commands:
    - composer install --dev

tools:

    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: [framework/*, tests/*]

    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: [framework/*, tests/*]

    php_mess_detector: false

    php_analyzer:
        enabled: true
        filter:
            paths: [framework/*, tests/*]

    php_code_coverage:
        enabled: true
        filter:
            paths: [framework/*, tests/*]

    sensiolabs_security_checker: false
