#
# scrutinizer-ci.com Configuration File
#
# https://scrutinizer-ci.com/docs/
#
before_commands:
    - sudo composer self-update
    - composer install --dev --prefer-source

filter:
    excluded_paths:
        - 'vendor/*'

tools:

    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: [framework/*, tests/*]

    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: [framework/*, tests/*]

    php_mess_detector:
        enabled: true
        config:
            rulesets:
                - codesize
                - unusedcode
                - naming

    php_analyzer:
        enabled: true
        filter:
            paths: [framework/*, tests/*]

    php_code_coverage:
        enabled: true
        test_command: phpunit -c tests/phpunit.xml.dist
        filter:
            paths: [framework/*, tests/*]

    sensiolabs_security_checker: false
