#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://docs.travis-ci.com/user/languages/php/ for more hints
#
language: php

# use container based infrastructure (no sudo possible)
sudo: false

cache:
  directory:
    - $HOME/.composer/cache/files

php: [5.5, 5.6, 7, hhvm]

matrix:
  allow_failures:
   - php: hhvm
  fast_finish: true

services: [memcached, mongodb]

before_install:
  - composer self-update
  - composer install --prefer-dist --no-interaction --optimize-autoloader
  - git submodule update --init --recursive

before_script:
  #- php ./bin/travis-setup.php $OPCODE_CACHE

script:
  - ant set-exec-permissions
  - ant php-cs-fixer
  - ant phpunit
  # - php ./bin/coverage-check.php ./build/logs/clover.xml 70

after_script:
  - php vendor/bin/coveralls -v
  - ant upload-codecoverage-to-scrutinizer

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true

# reduce commit history of git checkout
git:
  depth: 5
