#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

env:
  - OPCODE_CACHE=apc
  # MONGO_VERSION=1.3.7

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

services:
  - memcached
  - mongodb

before_script:
  # pecl -q install -f mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - php ./bin/travis-setup.php $OPCODE_CACHE

before_install:
  - composer self-update
  - composer install --dev --prefer-dist --no-interaction
  - git submodule update --init --recursive

script:
  # ant php-cs-fixer
  # ant utf8-encoding-check
  # ant phpcs
  - ant phpunit
  # - php ./bin/coverage-check.php ./build/logs/clover.xml 70

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: false
  irc: 
    channels: 
      - "irc.freenode.org#koch"
    use_notice: true  

# reduce commit history of git checkout
git:
  depth: 1
