#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

env:
  - OPCODE_CACHE=apc

php:
  - 5.3
  - 5.4
  - 5.5

services:
  - memcached

before_script: php ./bin/travis-setup.php $OPCODE_CACHE

before_install:
  - composer self-update
  - composer install --dev --prefer-dist
  - git submodule update --init --recursive

script:
  # ant php-cs-fixer
  # ant utf8-encoding-check
  # ant phpcs
  - ant phpunit
  - php ./bin/coverage-check.php ./tests/clover.xml 70

after_script:
  - php vendor/bin/coveralls

notifications:
  irc: "irc.freenode.org#koch"
  email: false

# reduce commit history of git checkout
git:
  depth: 30
