#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

php:
  - 5.3
  - 5.4

before_install:
  # - pear install pear/PHP_CodeSniffer-1.4.0
  # - phpenv rehash
  - composer install --dev
  - git submodule update --init --recursive

script:
  - php tests/runTests.php
  #
  # run php-cs-fixer
  #
  # - output=$(php ./bin/php-cs-fixer/php-cs-fixer.phar fix -v --level=all --dry-run .); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;
  #
  # run UTF8 encoding check
  #
  # ./bin/checkEncodingUTF8.sh framework
  #
  # run CodeSniffer
  #
  # phpcs --encoding=utf-8 --tab-width=4 --extensions=php --standard=PSR2 ./framework/Koch
  #
  # run unit-tests
  #
  # ./tests/runTests.sh

notifications:
  irc: "irc.freenode.org#koch"
  email: false
