<?php
namespace Koch\Router;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-03 at 00:24:34.
 */
class TargetRouteTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TargetRoute
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = TargetRoute::instantiate();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        unset($this->object);
    }

    /**
     * @covers Koch\Router\TargetRoute::instantiate
     * @todo   Implement testInstantiate().
     */
    public function testInstantiate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::setFilename
     * @todo   Implement testSetFilename().
     */
    public function testSetFilename()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getFilename
     * @todo   Implement testGetFilename().
     */
    public function testGetFilename()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::setClassname
     * @todo   Implement testSetClassname().
     */
    public function testSetClassname()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getClassname
     * @todo   Implement testGetClassname().
     */
    public function testGetClassname()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::setController
     * @todo   Implement testSetController().
     */
    public function testSetController()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getController
     */
    public function testGetController()
    {
        $this->assertEquals('Index', $this->object->getController());

        $this->object->setController('aController');
        $this->assertEquals('AController', $this->object->getController());
    }

    /**
     * @covers Koch\Router\TargetRoute::getModule
     * @todo   Implement testGetModule().
     */
    public function testGetModule()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::setModule
     * @todo   Implement testSetModule().
     */
    public function testSetModule()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::setAction
     * @todo   Implement testSetAction().
     */
    public function testSetAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getAction
     * @todo   Implement testGetAction().
     */
    public function testGetAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getActionNameWithoutPrefix
     * @todo   Implement testGetActionNameWithoutPrefix().
     */
    public function testGetActionNameWithoutPrefix()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::setId
     * @todo   Implement testSetId().
     */
    public function testSetId()
    {
        $this->assertEquals($this->object->getId(), $this->object->setId('1'));
    }

    /**
     * @covers Koch\Router\TargetRoute::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getActionName
     * @todo   Implement testGetActionName().
     */
    public function testGetActionName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::setMethod
     */
    public function testSetMethod()
    {
        $this->assertEquals('action_list', $this->object->getMethod());

        $this->object->setMethod('a-method');
        $this->assertEquals('a-method', $this->object->getActionName());

    }

    /**
     * @covers Koch\Router\TargetRoute::getMethod
     * @todo   Implement testGetMethod().
     */
    public function testGetMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::setParameters
     * @todo   Implement testSetParameters().
     */
    public function testSetParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getParameters
     * @todo   Implement testGetParameters().
     */
    public function testGetParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getFormat
     * @todo   Implement testGetFormat().
     */
    public function testGetFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::setRequestMethod
     * @todo   Implement testSetRequestMethod().
     */
    public function testSetRequestMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getRequestMethod
     * @todo   Implement testGetRequestMethod().
     */
    public function testGetRequestMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getLayoutMode
     * @todo   Implement testGetLayoutMode().
     */
    public function testGetLayoutMode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getAjaxMode
     * @todo   Implement testGetAjaxMode().
     */
    public function testGetAjaxMode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getRenderEngine
     * @todo   Implement testGetRenderEngine().
     */
    public function testGetRenderEngine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::setRenderEngine
     * @todo   Implement testSetRenderEngine().
     */
    public function testSetRenderEngine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getBackendTheme
     * @todo   Implement testGetBackendTheme().
     */
    public function testGetBackendTheme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getFrontendTheme
     * @todo   Implement testGetFrontendTheme().
     */
    public function testGetFrontendTheme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getThemeName
     * @todo   Implement testGetThemeName().
     */
    public function testGetThemeName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::setThemeName
     * @todo   Implement testSetThemeName().
     */
    public function testSetThemeName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getModRewriteStatus
     * @todo   Implement testGetModRewriteStatus().
     */
    public function testGetModRewriteStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::dispatchable
     * @todo   Implement testDispatchable().
     */
    public function testDispatchable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::setSegmentsToTargetRoute
     * @todo   Implement testSetSegmentsToTargetRoute().
     */
    public function testSetSegmentsToTargetRoute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::reset
     * @todo   Implement testReset().
     */
    public function testReset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::getRoute
     * @todo   Implement testGetRoute().
     */
    public function testGetRoute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::debug
     * @todo   Implement testDebug().
     */
    public function testDebug()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::set
     * @todo   Implement testSet().
     */
    public function testSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Koch\Router\TargetRoute::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
