<?php

/**
 * Koch Framework
 * Jens A. Koch © 2005 - onwards
 *
 * SPDX-License-Identifier: MIT
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

namespace Koch\Config\Adapter;

/**
 * Config Handler for PHP Format.
 *
 * @category    Koch
 * @package     Core
 * @subpackage  Configuration
 */
class Native
{
    /**
     * Read the config array from php file
     *
     * @param   string  The filename
     *
     * @return mixed array | bool false
     */
    public static function readConfig($file)
    {
        if (is_file($file) === false or is_readable($file) === false) {
            throw new \Koch\Exception\Exception('PHP Array Config File not existing or not readable.');
        }

        // it's a native php array structure so we simply include the file
        $array = include $file;

        if (is_array($array) === false) {
            throw new \InvalidArgumentException('PHP Array Config File does not contain array.');
        }

        return $array;
    }

    public static function writeConfig($file, array $array)
    {
        // transform the data structure to a more readable format
        $config_array = var_export($array, true);

        $format = "<?php\n" .
            "// Configuration File generated by Koch Framework.\n" .
            "// This file was generated on %s. \n" .
            "return %s;\n";

        $content = sprintf($format, date('d-m-Y H:i'), $config_array);

        // write to file
        return (bool) file_put_contents($file, $content);
    }
}
